name:                haskell-monopoly-game
version:             0.1.0.0
github:              "WhatsWithAlex/haskell-monopoly-game"
license:             BSD3
author:              "Alexey Korzhin"
maintainer:          "alexeykorzhin@mail.ru"
copyright:           "2022 Alexey Korzhin"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WhatsWithAlex/haskell-monopoly-game>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

library:
  source-dirs: src

executables:
  monopoly-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monopoly-game

tests:
  monopoly-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-monopoly-game
